[env]
TERM = 'xterm-256color'

[window]
padding.x = 10
padding.y = 10
dimensions.columns = 100
dimensions.lines = 30

decorations = "Buttonless"
opacity = 0.8 
blur = true

option_as_alt = 'Both'

[font]
normal.family = 'Iosevka'
size = 19
